apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: microservices
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
  labels:
    app: user-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: grpc
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
spec:
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: grpc
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
  labels:
    app: product-service
spec:
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: grpc
  selector:
    app: product-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices
  labels:
    app: payment-service
spec:
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: grpc
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
spec:
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: grpc
  selector:
    app: notification-service